const locationitem = [
    {
        locationId: 1,
        name: 'location 1',
        city: 'city 1',
        address: 'address 1',
        image: './images/location1.png',
        priceMinPerson: 1.11,
        priceMaxPerson: 2.22,
        timeOpen: 111,
        TimeClose: 222,
    },
    {
        locationId: 2,
        name: 'location 2',
        city: 'city 2',
        address: 'address 2',
        image: './images/location2.png',
        priceMinPerson: 1.11,
        priceMaxPerson: 2.22,
        timeOpen: 111,
        TimeClose: 222,
    },
    {
        locationId: 3,
        name: 'location 3',
        city: 'city 3',
        address: 'address 3',
        image: './images/location3.png',
        priceMinPerson: 1.11,
        priceMaxPerson: 2.22,
        timeOpen: 111,
        TimeClose: 222,
    },
    {
        locationId: 4,
        name: 'location 4',
        city: 'city 4',
        address: 'address 4',
        image: './images/location4.png',
        priceMinPerson: 1.11,
        priceMaxPerson: 2.22,
        timeOpen: 111,
        TimeClose: 222,
    },
];
export default locationitem;